#!/usr/bin/env bash

#
# A script for running a kitty subprocess to act as a graphical menu for input.
# The subprocess will take in a simple string and outputs to terminal.
# 
# Take note of the windowrule on `class:kitty-prompt` in hyprland configs:
# --> $XDG_CONFIG_HOME/hypr/hyprland-windowrules.conf
#

MY_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "$MY_DIR"/include/kitty/*
ID="${_ID}-prompt"

CALLER_ID=${1:-$ID} && shift
MENU_PROMPT=${1:-"Submit input"} && shift
MODE=${1:-"normal"}

WINDOW_WIDTH=600
WINDOW_HEIGHT=120

TMP="$(mktemp)"

READ_FLAGS=""
case "$MODE" in
    silent)
        READ_FLAGS="-s"
        ;;
    normal|*)
        READ_FLAGS="-r"
        ;;
esac

CMD="echo '$CALLER_ID | $MENU_PROMPT' && 
    printf %*s\\\\n \$(tput cols) | 
    tr ' ' '-' && 
    read line && 
    echo \$line > \"$TMP\""

TMP_CMD=$(mktemp)
chmod +x "$TMP_CMD"
echo "$CMD" > "$TMP_CMD"
kitty_spawn "$TMP_CMD" --class="$ID" --width="$WINDOW_WIDTH" --height="$WINDOW_HEIGHT" &&
    printf "%b" "$(cat $TMP)"
rm "$TMP" "$TMP_CMD"

