#!/usr/bin/env bash

#
# A script for running a kitty subprocess to act as a one-off text edit.
# Will take in an input file, and output the resulting editor buffer
# as stdout.
# 

MY_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "$MY_DIR"/include/kitty/*
ID="${_ID}-edit"

IN_FILE="$1" && shift
EDITOR_FLAGS="$1" && shift

EDITOR=${EDITOR:-nvim}

WINDOW_WIDTH=1200
WINDOW_HEIGHT=800

# If no file is provided, editor is opened with a blank buffer.
[ -z "$IN_FILE" ] && IN_FILE=$(mktemp) && echo "$IN_FILE"

CMD="$EDITOR $EDITOR_FLAGS $IN_FILE"
kitty_spawn "$CMD" --class="$ID" --width="$WINDOW_WIDTH" --height="$WINDOW_HEIGHT" &&
    [ -f "$IN_FILE" ] && echo "$IN_FILE"

