#!/usr/bin/env bash

#
# A script for running a window for running a single command. Will not return anything.
# 

MY_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "$MY_DIR"/include/kitty/*
ID="${ID}cmd"

CMD="$1"

WINDOW_WIDTH=800
WINDOW_HEIGHT=800

[ -z "$CMD" ] && echo "No command provided." && exit 1

kitty_spawn "$ID" "$WINDOW_WIDTH" "$WINDOW_HEIGHT" "$CMD"

