#!/usr/bin/env bash

#
# A script for running a window for running a single command. Will not return anything.
# 

WINDOW_WIDTH=800
WINDOW_HEIGHT=800

ID="kitty-cmd"
CMD="$1" && shift

kitty \
    --class kitty-cmd \
    --override="map Ctrl+Esc close" \
    --override="confirm_os_window_close 0" \
    --override="initial_window_width  $WINDOW_WIDTH" \
    --override="initial_window_height $WINDOW_HEIGHT" \
    bash -c "$CMD" 2> /dev/null

