#!/usr/bin/env bash

#
# Application Launcher
#

set -e

TITLE="launcher"
LAUNCH_PROMPT="Run a Command"
CONFIG_PROMPT="Select an Action"
EDITOR=${EDITOR:-"nvim"}

OPTS_FILE=$HOME/.launcher/options
OPTS_FILE_BACKUP="$XDG_CACHE_HOME/launcher/options_backup"
OPTS_FILE_RECENTS="$XDG_CACHE_HOME/launcher/recent"
if [ ! -d "$(dirname "$OPTS_FILE")" ]; then         mkdir -p "$(dirname "$OPTS_FILE")"; fi
if [ ! -d "$(dirname "$OPTS_FILE_BACKUP")" ]; then  mkdir -p "$(dirname "$OPTS_FILE_BACKUP")"; fi
if [ ! -d "$(dirname "$OPTS_FILE_RECENTS")" ]; then mkdir -p "$(dirname "$OPTS_FILE_RECENTS")"; fi

MODE=LAUNCH
if [[ "$@" =~ "--config" ]]; then MODE=CONFIG; fi

trim_whitespace() {
    while IFS= read -r LINE; do
        echo "$LINE" | awk '{$1=$1;print}'
    done
}

reset_recents() {
    if [[ "$@ " =~ "--force " || ! -f "$OPTS_FILE_RECENTS" ]]; then
        cp "$OPTS_FILE" "$OPTS_FILE_RECENTS"
    fi
}

restore_opts() {
    if [ -f "$OPTS_FILE_BACKUP" ]; then
        mv "$OPTS_FILE_BACKUP" "$OPTS_FILE"
    fi
    reset_recents --force
}

update_recents() {
    local CHOSEN_OPT="$1"
    local CHOSEN_CMD="$2"
    reset_recents
    local RECENTS_BUF=$(cat "$OPTS_FILE_RECENTS" | sed "\|^$CHOSEN_OPT|d")
    echo "$CHOSEN_OPT: $CHOSEN_CMD" >"$OPTS_FILE_RECENTS" # Overwrite
    echo "$RECENTS_BUF" >>"$OPTS_FILE_RECENTS"
}

get_opts() {
    local CUT="cat"
    local IN_FILE="$OPTS_FILE_RECENTS"
    reset_recents
    if [[ "$@ " =~ "--name " ]]; then CUT="cut -d: -f1"; fi
    if [[ "$@ " =~ "--cmd " ]]; then CUT="cut -d: -f2"; fi
    if [[ "$@ " =~ "--no_recent " ]]; then IN_FILE="$OPTS_FILE"; fi
    while IFS= read -r LINE; do
        echo "$LINE" | $CUT | trim_whitespace
    done <"$IN_FILE"
}

lookup_opt() {
    local OPT_NAME="$1"
    local CUR_NAME=
    local CUR_CMD=
    while IFS= read -r LINE; do
        CUR_NAME=$(echo "$LINE" | cut -d: -f1 | trim_whitespace)
        CUR_CMD=$(echo "$LINE" | cut -d: -f2 | trim_whitespace)
        if [ "$OPT_NAME" == "$CUR_NAME" ]; then
          echo "$CUR_CMD"
          return 0
        fi
    done <"$OPTS_FILE"
    return 1
}

update_opts() {
    local NAME=
    local CMD=
    local TMP=$(mktemp)
    editor_header >"$TMP"
    get_opts --no_recent >>"$TMP"
    local SUM=$(sha256sum "$TMP")
    "$EDITOR" "$TMP" '-c $'
    if [ "$SUM" == "$(sha256sum $TMP)" ]; then return 0; fi
    mv "$OPTS_FILE" "$OPTS_FILE_BACKUP"
    touch "$OPTS_FILE"
    while IFS= read LINE; do
        if [[ "$LINE" =~ ^'#' ]]; then continue; fi
        NAME=$(echo $LINE | cut -d':' -f1 | trim_whitespace)
        CMD=$(echo $LINE | cut -d':' -f2 | trim_whitespace)
        if [ -z "$NAME" ]; then continue; fi
        if [ -z "$CMD" ]; then CMD="$NAME"; fi
        printf "%s: %s\n" "$NAME" "$CMD" >>"$OPTS_FILE"
    done <"$TMP"
    reset_recents --force
    rm "$TMP"
}

editor_header() {
    echo "#####################################################"
    echo "###             ZMENU:LAUNCHER CONFIG             ###"
    echo "### _____________________________________________ ###"
    echo "### Add / edit entries in the following format:   ###"
    echo "### option1: command1                             ###"
    echo "### option2: command2                             ###"
    echo "### etc...                                        ###"
    echo "###                                               ###"
    echo "### Or simply enter the name of the command:      ###"
    echo "### command3                                      ###"
    echo "### command4                                      ###"
    echo "### etc...                                        ###"
    echo "#####################################################"
    echo "### A backup file will be created on edit.        ###"
    echo "### To abort, close this buffer.                  ###"
    echo "#####################################################"
    echo ""
}

config_mode() {
    local ID="$ID:config"
    local TMP_FILE=$(mktemp)
    local ACTION=$(
        fzf-select \
            --title "Launcher Configuration" \
            --prompt "Select an Action" \
            --opts "edit\nclear history\nrestore backup"
    )
    case $ACTION in
    edit)
        editor_header >"$TMP_FILE"
        get_opts --no_recent >>"$TMP_FILE"
        update_opts
        rm "$TMP_FILE"
        ;;
    restore*)
        echo "Restoring options..."
        restore_opts
        ;;
    clear*)
        echo "Clearing recents..."
        reset_recents --force
        ;;
    *)
        echo "ERROR: $ACTION is not an option"
        return 1
        ;;
    esac
    echo "Done."
    return 0
}

launch() {
  echo "$@"
    nohup $@ >/dev/null 2>&1 &
    sleep 0.01 # Give the process time to get a new pgid
}
launcher_mode() {
    local ID="$ID"
    local LAUNCHER_NAMES=$(get_opts --name)
    local OPT_NAME=$(
        fzf-select \
            --title "Launcher" \
            --prompt "$LAUNCH_PROMPT" \
            --opts "$LAUNCHER_NAMES"
    )
    if [ -z "$OPT_NAME" ]; then
      echo "Nothing chosen."
      return 1
    fi
    local OPT="$(lookup_opt "$OPT_NAME")"
    if [ -z "$OPT" ]; then
      echo "Invalid option: $OPT_NAME"
      return 1
    fi
    update_recents "$OPT_NAME" "$OPT"
    launch "$OPT"
}

case $MODE in
CONFIG)
    config_mode
    ;;
LAUNCH)
    echo "launcher_mode"
    launcher_mode
    ;;
esac
