#!/bin/bash

#UUID is hard coded
UUID='de60baf'
VAR=`lsblk -fs | grep $UUID | awk '{print $1}'`
echo "Looking for drive with UUID" $UUID
if [ -z $VAR ]
then
  echo "Hard drive not found in blkid. Is it inserted?"
  exit 1
else
  DISC="/dev/$VAR"
  MOUNT=`cat /proc/self/mounts | grep $DISC | awk '{print $1}'`
  if [ -z $MOUNT ]
  then
    #mount HDD
    udisksctl mount -b $DISC $HOME/ExHDD/
    echo "Hard drive" $DISC "successfully mounted."
  else
    echo "Hard drive" $DISC "already mounted."
  fi
fi

