#!/bin/env bash

#
# Selects a note with fzf and opens it in the editor
#

set -e

TITLE="Notes"
MYPROMPT="Select a Note"
NOTES_DIR="$HOME/Notes"
PREVIEW="cat '$NOTES_DIR/{}' 2> /dev/null || echo {}"
EDITOR=${EDITOR:-"nvim"}

[ ! -d "$NOTES_DIR" ] && mkdir -p "$NOTES_DIR"

CREATE_NEW='[ Create new... ]'

NOTE=$(
    fzf-files \
        --src "$NOTES_DIR" \
        --title "$TITLE" \
        --prompt "$MYPROMPT" \
        --preview "$PREVIEW" \
        --opt "$CREATE_NEW"
)

md_extension() { ! [[ "$1" =~ \.md$ ]] && echo "$1.md" || echo "$1"; }

if [[ "$NOTE" == "$CREATE_NEW" ]]; then
    TIMESTAMP="$(date +"%Y-%m-%dT%H:%M:%S%z")"
    FILENAME_DEFAULT="$NOTES_DIR/$TIMESTAMP.md"
    FILENAME="$NOTES_DIR/$(prompt -p "Enter a filename ( default: $TIMESTAMP.md )")"
    [ -z "$FILENAME" ] && FILENAME="$FILENAME_DEFAULT"
    ! [[ "$FILENAME" =~ ^"$NOTES_DIR" ]] && exit 1
    NOTE="$(md_extension "$FILENAME")"
fi

kitty --detach -d "$NOTES_DIR" /bin/bash -c "$EDITOR $NOTE"
