#!/usr/bin/env bash
set -e
_ID="ollama-start"
MY_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "$MY_DIR/include/util/log.sh"

if [ "$1" = "kill" ]; then
    log_info "$_ID" "Killing all ollama processes."
    pkill -9 ollama || true
    exit 0
fi

if pgrep -x ollama > /dev/null; then
    exit 0
fi

# start ollama server
nohup ollama serve &>/dev/null &
log_info "$_ID" "Started ollama server" --silent

