#!/bin/env bash

# 
# Application Launcher
#

set -e

TITLE="Session"
PROMPT="Select an Action"
EDITOR=${EDITOR:-"nvim"}

OPTS="logout\nlock\nsleep\nshutdown\nreboot"

OPT=$(fzf-select --title "$TITLE" --prompt "select an action" --opts "$OPTS")

case $OPT in
    "logout")
        hyprctl dispatch exit
        ;;
    "lock")
        hyprlock
        ;;
    "sleep")
        systemctl suspend
        ;;
    "shutdown")
        shutdown -ah now
        ;;
    "reboot")
        shutdown -ar now
        ;;
    *)
        exit 1
esac

