#!/usr/bin/env bash

# This is a script for graphical menu subscripts
# These are tailored towards a "dmenu-like" interface, but can be retooled
# Supported functions:
# audio | convert | notes | scaling | session | zeit
#
_ID="zmenu"

MY_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
ZMENU_INCLUDE_DIR="$MY_DIR/include/zmenu"
UTIL_DIR="$MY_DIR/include/util"

source "$UTIL_DIR/log.sh"
source "$ZMENU_INCLUDE_DIR/input.sh"

MODULE=$1
[ -z "$MODULE" ] &&
    OPTS=$( ls -t --color=none -1 "$ZMENU_INCLUDE_DIR/modules" | sed -e 's/\.sh//g') &&
    MODULE=$(d_read "$_ID" "$OPTS" "Select a menu option")
[ -z "$MODULE" ] && exit 1

[ ! -f "$ZMENU_INCLUDE_DIR/modules/$MODULE.sh" ] &&
    log_error "$_ID" "Module not found: $MODULE" && exit 1

# Invoke the module
shift && source "$ZMENU_INCLUDE_DIR/modules/$MODULE.sh"

