#!/usr/bin/env bash

# This is a script for graphical menu subscripts
# These are tailored towards a "dmenu-like" interface, but can be retooled
# Supported functions:
# audio | convert | notes | scaling | session | zeit
#
_ID="zmenu"
UTIL_DIR=${UTIL_DIR:-"$XDG_CONFIG_HOME/scripts/include/util"}
ZMENU_INCLUDE_DIR=${ZMENU_INCLUDE_DIR:-"$XDG_CONFIG_HOME/scripts/include/zmenu"}
source "$UTIL_DIR/log.sh"
source "$ZMENU_INCLUDE_DIR/util.sh"

MODULE=$1
[ -z "$MODULE" ] &&
    OPTS=$(
        ls -t --color=none -1 "$ZMENU_INCLUDE_DIR/modules" | sed -e 's/\.sh//g'
    ) &&
    MODULE=$(d_read "$ID" "$OPTS" "Select a menu option") &&
    [ -z "$MODULE" ] && log_info "$ID" "No module selected" && exit 1

[ ! -f "$ZMENU_INCLUDE_DIR/modules/$MODULE.sh" ] &&
    log_error "$ID" "Module not found: $MODULE" && exit 1

# Invoke the module
source "$ZMENU_INCLUDE_DIR/modules/$MODULE.sh"

