#!/bin/echo Please-Source

ID_HYPRPAPER="$_ID:hyprpaper"

# Get config
[ -z "$HYPRPAPER_CONFIG" ] && HYPRPAPER_CONFIG="$XDG_CONFIG_HOME/hypr/hyprpaper.conf"

WALLPAPER_DIR="$THEME_HOME/$THEME/wallpapers"
WALLPAPERS=$(find "$WALLPAPER_DIR" -type f 2>/dev/null | shuf)

_is_active() {
    ! command -v hyprpaper >/dev/null && return 1
    [ -z "$WALLPAPERS" ] || [ ! -d "$WALLPAPER_DIR" ] &&
        pgrep -f hyprpaper >/dev/null && killall hyprpaper >/dev/null && return 1
    return 0
}

_monitors() {
    echo $(hyprctl monitors -j | jq -r -r '.[] | .name')
}

hyprpaper_theme() {
    local ID="$ID_HYPRPAPER:theme"
    ! _is_active && return 0
    MONITORS=($(_monitors))
    # Overwrite config file (clean not required)
    echo "# This file was generated by themectl" >"$HYPRPAPER_CONFIG" || return 1
    i=1
    for MONITOR in "${MONITORS[@]}"; do
        WALLPAPER=$(echo "$WALLPAPERS" | head -n $i | tail -n 1)
        echo "preload = $WALLPAPER" >>"$HYPRPAPER_CONFIG"
        echo "wallpaper {" >>"$HYPRPAPER_CONFIG"
        echo "  monitor = $MONITOR" >>"$HYPRPAPER_CONFIG"
        echo "  path = $WALLPAPER" >>"$HYPRPAPER_CONFIG"
        echo "  fit_mode = cover" >>"$HYPRPAPER_CONFIG"
        echo "}" >>"$HYPRPAPER_CONFIG"
        i=$(($i + 1))
    done
}

hyprpaper_reload() {
    local ID="$ID_HYPRPAPER:reload"
    # Kill hyprpaper if there are no wallpapers
    killall -9 hyprpaper
    if _is_active; then
      hyprpaper &
    fi
}

hyprpaper_clean() {
    ID="$ID_HYPRPAPER:clean"
    log_trace "$ID" "Nothing done."
}
