#!/bin/echo Please-Source

ID_WMENU="$_ID:wmenu"
TC_WMENU="$TC_DIR/wmenu"

[ -f "$TC_WMENU/config" ] &&
    CONFIG_FILE="$TC_WMENU/config" ||
    CONFIG_FILE="$TC_DEFAULT/wmenu/config"

[ -f "$TC_WMENU/flags" ] &&
    FLAGS_FILE="$TC_WMENU/flags" ||
    FLAGS_FILE="$TC_DEFAULT/wmenu/flags"

WMENU_OUT="$HOME/.local/bin/wmenu-wrapper"
WMENU_RUN_OUT="$HOME/.local/bin/wmenu-run-wrapper"

source "$CONFIG_FILE"

subst_line() {
    local ID="$ID_WMENU:subst_line"
    local LINE=$1
    local MATCHES=$(echo "$LINE" | grep -o '{_\([A-Z0-9_]\+\)_}')
    for MATCH in $MATCHES; do
        EXPR=$(echo "$MATCH" | sed 's/{_\(.*\)_\}/\1/')
        case $EXPR in
            COLOR_*)
                local COLOR_CODE=${EXPR#COLOR_}
                local COLOR_VALUE=$(themecolor $COLOR_CODE no_color no_fmt)
                COLOR_VALUE="${COLOR_VALUE:1}" # Everything but first char ('#')
                LINE=$(sed -e "s|{_${EXPR}_}|${COLOR_VALUE}|g" <<< "$LINE")
                ;;
            WMENU_*)
                local OPTION_VALUE=${!EXPR} # From wmenu config file
                [ -z "$OPTION_VALUE" ] && 
                    log_error "$ID" "Could not identify option: $EXPR" && return 1
                LINE=$(sed -e "s|{_${EXPR}_}|${OPTION_VALUE}|g" <<< "$LINE")
                ;;
            *)
                log_error "$ID" "Unrecognized expression in wmenu flags: $EXPR" && return 1
                ;;
        esac
    done
    echo -n "$LINE"
}

# The commands to copy theme files to a service
wmenu_theme() {
    local ID="$ID_WMENU:theme"
    touch "$WMENU_OUT"
    echo "# This file is auto-generated by $ID" > "$WMENU_OUT"
    echo -n "wmenu " >> "$WMENU_OUT"
    while IFS= read -r LINE; do
        echo -n "$(subst_line "$LINE" "$CONFIG_FILE") " >> "$WMENU_OUT"
    done < "$FLAGS_FILE"
    cat "$WMENU_OUT" | sed -e "s|wmenu |wmenu-run |g" > "$WMENU_RUN_OUT"
    echo "\"\$@\"" >> "$WMENU_OUT" # To allow for additional flags
    echo "-p wmenu-run" >> "$WMENU_RUN_OUT"
    chmod +x "$WMENU_OUT"
    chmod +x "$WMENU_RUN_OUT"
}

# The command to reload the service, once themed
wmenu_reload() {
    local ID="$ID_WMENU:reload"
    echo "$ID: Nothing done."
}

# The command to un-theme a service
wmenu_clean() {
    local ID="$ID_WMENU:clean"
    rm -rf "$WMENU_OUT" "$WMENU_RUN_OUT"
}

