#!/bin/echo Please-Source

ID="$_ID:scaling"

# TODO: Allow selection of different monitors
PRIMARY_MON="eDP-1"

OUT_FILE="${HYPR_CONFIG_DIR:-"$HOME/.config/hypr"}/hyprland-scaling.conf"
HEADER="This file is generated by the $ID script."
MENU_PROMPT="Select scaling of primary monitor"
SCALING_VALUES=(75 100 125 150)
DEFAULT_SCALE="${SCALING_VALUES[2]}"

CURRENT_SCALE=$(
    cat "$OUT_FILE" | tail -n 2 | head -n 1 | cut -d "=" -f2 | xargs
)

percent_to_decimal() {
    local PERCENT=$1
    printf "%b.%b%b" \
        $(bc <<< "($PERCENT /100 ) % 10") \
        $(bc <<< "($PERCENT /10  ) % 10") \
        $(bc <<< "($PERCENT      ) % 10")
}

decimal_to_percent() {
    local DECIMAL=$1
    printf "%d%%\n" $(bc <<< "($DECIMAL*100)")
}

OPTS="${DEFAULT_SCALE}% (default)\n"
CURRENT_VALUE=$(decimal_to_percent $CURRENT_SCALE)
for VALUE in "${SCALING_VALUES[@]}"; do
    OPTS+="$VALUE%"
    [ "$CURRENT_VALUE" = "$VALUE%" ] && OPTS+=" (current)"
    OPTS+="\n"
done
OPT=$(d_read "$ID" "$OPTS" "$MENU_PROMPT" | cut -d'%' -f1)
[ -z $OPT] && exit 1

case $OPT in
    *'(default)')
        SCALE=$(percent_to_decimal $DEFAULT_SCALE)
        ;;
    [0-9][0-9]  | [0-9][0-9][0-9]  | \
    [0-9][0-9]% | [0-9][0-9][0-9]% )
        SCALE_P=$(echo "$OPT" | tr -d "%")
        [ "$SCALE_P" -lt "$SCALE_MIN" ] || [ "$SCALE_P" -gt "$SCALE_MAX" ] &&
            log_error $ID "Invalid scale: $SCALE" && exit 1
        SCALE=$(percent_to_decimal $SCALE_P)
        ;;
    *)
        log_error $ID "Invalid option: $OPT"
        exit 1
        ;;
esac

echo "# ${HEADER}" > "$OUT_FILE"
echo -e "\$monScale0 = ${SCALE}\n" >> "$OUT_FILE"
hyprctl reload

